#!/usr/bin/env node
'use strict';

// Runtime owns StorageManager and Window values. DOM retains their interfaces.
// TS7's anonymous constructor declarations conflict with the Runtime's values.
// Adapt only those two values in a generated DOM copy; do not rename DOM types.
// Keep the upstream interfaces and all other declarations checked with no skips.
const fs = require('node:fs');
const path = require('node:path');
const os = require('node:os');
const { spawnSync } = require('node:child_process');

const root = path.resolve(__dirname, '../..');
// Installed declaration bundles can use the consuming TS workspace's compiler.
// Keep the output beside this tool so relative declaration references still work.
const compilerRootIndex = process.argv.indexOf('--compiler-root');
if (compilerRootIndex !== -1 && (!process.argv[compilerRootIndex + 1] ||
    process.argv[compilerRootIndex + 1].startsWith('--'))) {
    throw new Error('--compiler-root requires a workspace directory.');
}
const compilerRoot = compilerRootIndex === -1 ? root : path.resolve(process.argv[compilerRootIndex + 1]);
const compilerPackage = [
    path.join(compilerRoot, 'node_modules/typescript/package.json'),
    path.join(compilerRoot, 'editor/node_modules/typescript/package.json'),
].find(file => fs.existsSync(file));
if (!compilerPackage) throw new Error('Install the pinned TypeScript development dependency first.');
const compilerInfo = JSON.parse(fs.readFileSync(compilerPackage, 'utf8'));
if (compilerInfo.version !== '7.0.2') {
    throw new Error('The DOM adapter is verified for TypeScript 7.0.2. Review it before upgrading.');
}
const compiler = path.resolve(path.dirname(compilerPackage), compilerInfo.bin.tsc);
function compile(args, options = {}) {
    const result = spawnSync(process.execPath, [compiler, ...args], {
        cwd: root, encoding: 'utf8', ...options,
    });
    if (result.error) throw result.error;
    return result;
}

const probe = fs.mkdtempSync(path.join(os.tmpdir(), 'rpgreactor-dom-'));
try {
    fs.writeFileSync(path.join(probe, 'empty.ts'), 'export {};\n');
    fs.writeFileSync(path.join(probe, 'tsconfig.json'), JSON.stringify({
        compilerOptions: { target: 'ES2022', lib: ['ES2022', 'DOM'], types: [], noEmit: true },
        files: ['empty.ts'],
    }));
    // Resolve the actual platform/compiler library via the public CLI, not the
    // removed TS5 compiler API or hardcoded native package/OS names.
    const listed = compile(['--listFilesOnly', '-p', path.join(probe, 'tsconfig.json')]);
    if (listed.status !== 0) throw new Error(listed.stdout + listed.stderr);
    const domFiles = listed.stdout.split(/\r?\n/).filter(file => /[/\\]lib\.dom\.d\.ts$/.test(file));
    if (domFiles.length !== 1) throw new Error('Expected exactly one TypeScript DOM library.');
    const source = fs.readFileSync(domFiles[0], 'utf8');
    const constructor = /^declare var StorageManager: \{\r?\n    prototype: StorageManager;\r?\n    new\(\): StorageManager;\r?\n\};/gm;
    if ([...source.matchAll(constructor)].length !== 1) {
        throw new Error('StorageManager DOM declaration changed; review the adapter.');
    }
    let adapted = source.replace(constructor,
        '// StorageManager constructor value is supplied by RPGReactor; DOM interface retained.');
    const windowConstructor = /^declare var Window: \{\r?\n    prototype: Window;\r?\n    new\(\): Window;\r?\n\};/gm;
    if ([...source.matchAll(windowConstructor)].length !== 1) {
        throw new Error('Window DOM constructor declaration changed; review the adapter.');
    }
    adapted = adapted.replace(windowConstructor,
        '// Window constructor value is supplied by RPGReactor; DOM interface retained for window/Pixi.');
    const output = path.join(root, 'types/compat/lib.dom.generated.d.ts');
    const content = '// GENERATED by types/tools/typecheck.cjs; do not edit.\n' + adapted;
    if (!fs.existsSync(output) || fs.readFileSync(output, 'utf8') !== content) {
        fs.writeFileSync(output, content);
    }
} finally {
    fs.rmSync(probe, { recursive: true, force: true });
}

if (process.argv.includes('--prepare')) {
    console.log('Prepared the TypeScript 7.0.2 DOM declarations for RPGReactor.');
} else {
    const result = compile(['--noEmit', '-p', path.join(root, 'tsconfig.types.json')], { stdio: 'inherit' });
    if (result.status !== 0) {
        process.exitCode = result.status ?? 1;
    } else {
        // .ts expect-error fixtures alone do not detect skipLibCheck being
        // enabled. A deliberately broken declaration must still be diagnosed.
        const guard = fs.mkdtempSync(path.join(os.tmpdir(), 'rpgreactor-dts-'));
        try {
            fs.writeFileSync(path.join(guard, 'invalid.d.ts'),
                'declare const declarationCheckGuard: RPGReactorMissingTypeGuard;\n');
            fs.writeFileSync(path.join(guard, 'tsconfig.json'), JSON.stringify({
                extends: path.join(root, 'tsconfig.types.json'),
                files: ['invalid.d.ts'],
            }));
            const negative = compile(['--noEmit', '-p', path.join(guard, 'tsconfig.json')]);
            if (negative.status === 0 || !/TS2304[^\n]*RPGReactorMissingTypeGuard/.test(negative.stdout + negative.stderr)) {
                throw new Error('Declaration checking is not active: the invalid .d.ts guard must report TS2304.');
            }
            console.log('Runtime type fixtures and strict declaration-check guard passed.');
        } finally {
            fs.rmSync(guard, { recursive: true, force: true });
        }
    }
}
