const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const B=require('../../runtime/reactor_battle_data.js');
const sequence=(steps,purpose='routine',extra={})=>({id:1,version:1,purpose,steps,...extra});
const context=()=>({homes:{user:{x:0,y:0,z:0},target:{x:5,y:0,z:0}}});
function harness(){
 const calls=[],state={switches:{},variables:{},gold:0};
 const battler=id=>({id,hp:100,mp:30,tp:0,mhp:100,mmp:30,maxTp:()=>100,isAlive(){return this.hp>0;},isDead(){return !this.isAlive();},isAppeared:()=>true,canMove:()=>true,isActor:()=>id===0,actorId:()=>id,clearResult(){},gainHp(v){this.hp+=v;},gainMp(v){this.mp+=v;},gainTp(v){this.tp+=v;},addState(v){calls.push(['state',id,v]);},deathStateId:()=>1,addBuff(...v){calls.push(['buff',...v]);},startDamagePopup(){},elementRate:id=>id/10});
 const user=battler(0),a=battler(1),b=battler(2),targets=[a,a,b];user.friendsUnit=()=>({members:()=>[user]});user.opponentsUnit=()=>({members:()=>[a,b]});
 const sprite=x=>({x,y:200,_homeX:x,_homeY:200,_offsetX:0,_offsetY:0,opacity:255,rotation:0,scale:{x:1,y:1,set(x,y=x){this.x=x;this.y=y;}},tone:[0,0,0,0],getColorTone(){return this.tone;},setColorTone(v){this.tone=v;},getBlendColor:()=>[0,0,0,0],setBlendColor(){},startMotion(name){this.motion=name;}});
 const sprites=new Map([[user,sprite(50)],[a,sprite(300)],[b,sprite(500)]]),action={item:()=>({damage:{type:1}}),makeDamageValue(){return 100;},evalDamageFormula(){return 99;},calcElementRate(){return 1;}};
 const manager={_action:action,_targets:targets.slice(),_spriteset:{findTargetSprite:b=>sprites.get(b)},invokeAction(user,target){calls.push(['hit',target.id,action.makeDamageValue(target),action.evalDamageFormula(target),action.calcElementRate(target)]);}};
 const globals={ReactorBattleData:B,DataManager:{isDatabaseLoaded:()=>true},SceneManager:{},console,$gameParty:{battleMembers:()=>[user],gainGold:v=>state.gold+=v},$gameTroop:{members:()=>[a,b]},$gameSwitches:{value:id=>state.switches[id]||false,setValue:(id,v)=>state.switches[id]=v},$gameVariables:{_data:[],value:id=>state.variables[id]||0,setValue:(id,v)=>state.variables[id]=v}};
 vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../../runtime/reactor_battle_presentation.js'),'utf8'),globals);
 const P=globals.ReactorBattlePresentation,adapter=P.adapter(manager,user,targets);return {P,adapter,manager,user,a,b,sprites,calls,state,action,globals};
}
test('editor and runtime share all command definitions byte for byte',()=>{assert.equal(fs.readFileSync(path.join(__dirname,'../src/battle/BattleData.js'),'utf8'),fs.readFileSync(path.join(__dirname,'../../runtime/reactor_battle_data.js'),'utf8'));for(const type of Object.keys(B.commands))assert.deepEqual(B.validateSequence(sequence([B.step(type,{name:'Fixture'})],'routine')).filter(e=>!e.includes('If')),[],type);});
test('phase assignments resolve skill → weapon → class → battler and splice effect at contact',()=>{
 const settings=B.empty(),seq=[null,...B.actionPhases.map(([p],i)=>({...B.defaultPhase(p,{isAttack:true}),id:i+1}))];
 settings.actors[1]={mode:'phases',phases:{movement:{mode:'sequence',sequenceId:2}}};settings.classes[2]={mode:'phases',phases:{prepare:{mode:'sequence',sequenceId:1}}};settings.weapons[3]={mode:'phases',phases:{execute:{mode:'sequence',sequenceId:3}}};settings.skills[4]={mode:'phases',phases:{effect:{mode:'sequence',sequenceId:4}}};
 const resolved=B.resolvePresentation(settings,seq,{kind:'skills',itemId:4,isAttack:true,weaponIds:[3],classId:2,battlerKind:'actors',battlerId:1});assert.deepEqual(B.validateSequence(resolved.sequence),[]);assert.equal(resolved.phases.find(p=>p.phase==='movement').source.kind,'actors');assert.equal(resolved.phases.find(p=>p.phase==='effect').source.kind,'skills');assert.equal(resolved.sequence.steps.filter(s=>s.type==='impact').length,1);assert.equal(resolved.sequence.steps.find(s=>s.type==='impact').phase,'effect');
 settings.skills[4]={mode:'existing'};assert.equal(B.resolve(settings,seq,{kind:'skills',itemId:4}),null);
});
test('wrong purpose cannot be assigned as a complete action or a phase',()=>{const settings=B.empty();settings.skills[1]={mode:'sequence',sequenceId:1};assert.equal(B.resolve(settings,[null,B.defaultPhase('movement')],{kind:'skills',itemId:1}),null);settings.skills[1]={mode:'phases',phases:{execute:{mode:'sequence',sequenceId:1}}};assert.equal(B.resolve(settings,[null,B.template()],{kind:'skills',itemId:1}),null);});
test('authored impacts opt in to multiple hits while old sequences reject them',()=>{const s=sequence([B.step('impact'),B.step('impact')],'action');assert.ok(B.validateSequence(s).length);s.hitPolicy='authored';assert.deepEqual(B.validateSequence(s),[]);const h=harness();h.adapter.hitPolicy='authored';h.adapter.cue(B.step('impact',{role:'target',targetIndex:1,rate:50}),0);assert.deepEqual(h.calls[0],['hit',2,50,99,1]);assert.equal(h.manager._targets.length,0);h.adapter.cue(B.step('impact',{role:'target',targetIndex:1,rate:75}),0);assert.equal(h.calls[1][2],75);assert.equal(h.action.makeDamageValue(),100);});
test('default impact drains the original repeat occurrences and restores formula/element overrides',()=>{const h=harness();h.adapter.cue(B.step('formula',{formula:'40'}),0);h.adapter.cue(B.step('element',{elements:'2,7'}),0);h.adapter.cue(B.step('impact'),0);while(h.adapter.pendingImpact)h.adapter.resolveNext();assert.deepEqual(h.calls.map(c=>c[1]),[1,1,2]);assert.equal(h.calls[0][3],40);assert.equal(h.calls[0][4],.7);assert.equal(h.action.evalDamageFormula(),99);assert.equal(h.action.calcElementRate(),1);});
test('nested condition branches skip commands and their duration',()=>{
 const steps=[B.step('branch',{condition:'false',duration:0}),B.step('wait',{duration:100}),B.step('else',{duration:0}),B.step('branch',{condition:'true',duration:0}),B.step('sound',{duration:0}),B.step('end',{duration:0}),B.step('end',{duration:0}),B.step('wait',{duration:2})],cues=[];
 const player=new B.Player(sequence(steps),{context:context(),condition:code=>code==='true',cue:s=>cues.push(s.type)});for(let i=0;i<5;i++)player.update();assert.equal(player.done,true);assert.deepEqual(cues,['sound','wait']);assert.equal(player.duration,2);
});
test('invalid branches and recursive calls are rejected',()=>{assert.ok(B.validateSequence(sequence([B.step('else')])).length);assert.ok(B.validateSequence(sequence([B.step('branch')])).length);const s=sequence([B.step('action',{sequenceId:1})]);assert.throws(()=>B.expandCalls(s,[null,s]),/Recursive/);assert.throws(()=>B.expandCalls(s,[null]),/Missing/);});
test('routine calls expand without mutating sources',()=>{const routine=sequence([B.step('sound')]),action=sequence([B.step('action',{sequenceId:1}),B.step('impact')],'action'),before=JSON.stringify(action);const expanded=B.expandCalls(action,[null,routine]);assert.deepEqual(expanded.steps.map(s=>s.type),['sound','impact']);assert.equal(JSON.stringify(action),before);assert.deepEqual(B.validateSequence(expanded),[]);});
test('target filtering preserves unique visible slots and supports dead/random/actor ID',()=>{const h=harness(),c={user:h.user,targets:[h.a,h.a,h.b],enemies:[h.a,h.b],actors:[h.user],random:()=>.99};assert.deepEqual(B.selectTargets({role:'target',targetIndex:1},c),[h.b]);assert.deepEqual(B.selectTargets({role:'enemies',filter:'random'},c),[h.b]);h.a.hp=0;assert.deepEqual(B.selectTargets({role:'enemies',filter:'dead'},c),[h.a]);});
test('resource, switch, variable and inventory commands affect selected battlers only',()=>{const h=harness();h.adapter.cue(B.step('hp',{role:'target',targetIndex:1,amount:'-25'}),0);assert.equal(h.a.hp,100);assert.equal(h.b.hp,75);h.adapter.cue(B.step('mp',{role:'user',amount:'-50',percent:'percent'}),0);assert.equal(h.user.mp,15);h.adapter.cue(B.step('switch',{switchId:2,operation:'toggle'}),0);h.adapter.cue(B.step('variable',{variableId:3,amount:'8'}),0);h.adapter.cue(B.step('variable',{variableId:3,operation:'multiply',amount:'2'}),0);h.adapter.cue(B.step('item',{kind:'gold',amount:'25'}),0);assert.equal(h.state.switches[2],true);assert.equal(h.state.variables[3],16);assert.equal(h.state.gold,25);});
test('opacity, tint, lift and held poses restore after cancellation',()=>{const h=harness(),sprite=h.sprites.get(h.user);h.adapter.cue(B.step('opacity',{opacity:0,duration:10}),0);h.adapter.cue(B.step('tint',{red:100,duration:10}),0);h.adapter.cue(B.step('float',{height:2,duration:10}),0);h.adapter.cue(B.step('pose',{frame:2}),0);h.adapter.pose(h.adapter.context.homes,5);assert.equal(sprite.opacity,127.5);assert.equal(sprite.tone[0],50);assert.equal(sprite._rrLift,1);h.adapter.cleanup(true);assert.equal(sprite.opacity,255);assert.deepEqual(sprite.tone,[0,0,0,0]);assert.equal(sprite._rrLift,0);assert.equal(sprite._rrHeldPose,undefined);});
test('blocking common events cancel with the player',()=>{let running=true,cancelled=false;const player=new B.Player(sequence([B.step('wait')]),{context:context(),cue:()=>({blocking:true,isPlaying:()=>running,cancel(){running=false;cancelled=true;}})});player.update();assert.ok(player.waiting);player.cancel();assert.equal(cancelled,true);});
test('graphic selection separates explicit sprite, static and model types from legacy models',()=>{const settings=B.empty(),record={battlerName:'Actor1'},legacy={name:'Robot'};assert.equal(B.graphic(settings,'actors',1,record,legacy).type,'model');settings.actors[1]={graphic:{mode:'character',name:'People',index:5}};assert.equal(B.graphic(settings,'actors',1,record,legacy).folder,'characters');settings.actors[1].graphic.mode='static';assert.equal(B.graphic(settings,'actors',1,record,legacy).type,'static');});
test('custom SV and character sheet crops stay inside images across dimensions',()=>{for(const size of [8,16,24,32,48,64,288])for(const graphic of [{type:'sv',frames:3,motionColumns:3,motionRows:6},{type:'sv',frames:4,motionColumns:1,motionRows:14},{type:'character',name:'People',index:7},{type:'character',name:'!$Hero',index:0}]){const w=(graphic.type==='sv'?(graphic.frames*graphic.motionColumns):graphic.name.includes('$')?3:12)*size,h=(graphic.type==='sv'?graphic.motionRows:graphic.name.includes('$')?4:8)*size;for(const motion of Object.keys(B.spriteMotions)){const f=B.graphicFrame(graphic,w,h,motion,999);assert.equal(f.width,size);assert.equal(f.height,size);assert.ok(f.x>=0&&f.y>=0&&f.x+f.width<=w&&f.y+f.height<=h,JSON.stringify({graphic,f}));}}});
test('motion frame override cannot escape the sprite cell and once holds the final frame',()=>{const graphic={type:'sv',frames:3,motions:{idle:{frames:999,loop:'once',index:0,speed:1}}};const f=B.graphicFrame(graphic,576,384,'idle',1000);assert.equal(f.x,128);assert.equal(f.width,64);});
test('class state choices override actors and explicit existing motion stops inheritance',()=>{const settings=B.empty(),seq=sequence([B.step('motion',{motion:'idle'})],'motion');settings.actors[1]={states:{idle:{mode:'sequence',sequenceId:1}}};assert.equal(B.resolveState(settings,[null,seq],'actors',1,'idle',2),seq);settings.classes[2]={states:{idle:{mode:'existing'}}};assert.equal(B.resolveState(settings,[null,seq],'actors',1,'idle',2),null);});
test('presentation media commands release their layers and restore windows and backdrops',()=>{
 const h=harness(),events=[],children=[];
 class Graphic{constructor(bitmap){this.bitmap=bitmap;this.opacity=255;this.anchor={set(){}};this.scale={set(){}};this.origin={x:0,y:0};}setFrame(...v){this.frame=v;}move(...v){this.rect=v;}removeFromParent(){const i=children.indexOf(this);if(i>=0)children.splice(i,1);}destroy(){this.destroyed=true;}}
 class Balloon extends Graphic{setup(...v){this.setupArgs=v;}update(){}}
 const ss=h.manager._spriteset;ss._battleField={addChild:g=>children.push(g),addChildAt:g=>children.push(g)};ss._back1Sprite={bitmap:'floor'};ss._back2Sprite={bitmap:'background'};
 Object.assign(h.globals,{Sprite:Graphic,TilingSprite:Graphic,Sprite_Balloon:Balloon,ImageManager:{iconWidth:48,loadPicture:name=>({name,width:64,height:64}),loadSystem:name=>({name}),loadBattleback1:name=>name,loadBattleback2:name=>name},$gameScreen:{tone:()=>[0,0,0,0],startTint:v=>events.push(['tint',v]),startFlash:v=>events.push(['flash',v]),startShake:(...v)=>events.push(['shake',v])},AudioManager:{playBgm:v=>events.push(['bgm',v]),saveBgm:()=>({name:'saved'}),replayBgm:v=>events.push(['resume',v])}});
 h.globals.SceneManager._scene={_statusWindow:{visible:true}};
 h.adapter.cue(B.step('picture',{name:'Picture',index:2,x:12,y:-20}),0);h.adapter.cue(B.step('icon',{iconIndex:17,index:3}),0);h.adapter.cue(B.step('plane',{name:'Sky',index:4}),0);h.adapter.cue(B.step('balloon',{balloonId:2}),0);assert.equal(children.length,4);
 h.adapter.cue(B.step('battlestatus',{operation:'hide'}),0);assert.equal(h.globals.SceneManager._scene._statusWindow.visible,false);
 h.adapter.cue(B.step('battleback',{floor:'Desert',background:'Clouds'}),0);assert.equal(ss._back1Sprite.bitmap,'Desert');
 h.adapter.cue(B.step('bgm',{operation:'save'}),0);h.adapter.cue(B.step('bgm',{operation:'resume'}),0);assert.equal(events.at(-1)[1].name,'saved');
 h.adapter.cue(B.step('flash'),0);h.adapter.cue(B.step('shake'),0);h.adapter.pose(h.adapter.context.homes,5);
 h.adapter.cleanup(true);assert.equal(children.length,0);assert.equal(ss._back1Sprite.bitmap,'floor');assert.equal(ss._back2Sprite.bitmap,'background');assert.equal(h.globals.SceneManager._scene._statusWindow.visible,true);
});
test('common events block until their own interpreter finishes and scripts retain action context',()=>{
 const h=harness();class Interpreter{setup(list){this.remaining=list.length;}update(){this.remaining--;}isRunning(){return this.remaining>0;}clear(){this.remaining=0;}}
 Object.assign(h.globals,{Game_Interpreter:Interpreter,$dataCommonEvents:[null,{list:[1,2,3]}]});const ticket=h.adapter.cue(B.step('event',{eventId:1}),0);assert.equal(ticket.blocking,true);assert.equal(ticket.isPlaying(),true);assert.equal(ticket.isPlaying(),true);assert.equal(ticket.isPlaying(),false);
 h.adapter.cue(B.step('eval',{code:'user.gainHp(-7);'}),0);assert.equal(h.user.hp,93);assert.throws(()=>h.adapter.cue(B.step('event',{eventId:99}),0),/Missing common event/);
});
test('routine references protect called records and previews never execute authored scripts',()=>{
 const routine=sequence([B.step('eval',{code:'throw new Error("must not run in preview")'}),B.step('jump',{height:2,duration:20})]);const caller=sequence([B.step('action',{sequenceId:1})]);caller.id=2;assert.deepEqual(B.references(B.empty(),1,[null,routine,caller]),[{kind:'actionSequences',id:2,slot:'Call Sequence'}]);const plan=B.previewPlan(caller,[null,routine,caller]);const visual=B.previewVisuals(plan,10,context());assert.equal(visual.poses.user.z,2);assert.equal(visual.trace[0].label,'Run Script');
});
test('media steps require a file before activation',()=>{for(const type of ['movie','bgm','bgs','se','picture','plane']){assert.ok(B.validateSequence(sequence([B.step(type)])).includes('No file selected'),type);assert.ok(!B.validateSequence(sequence([B.step(type,{name:'Fixture'})])).includes('No file selected'),type);}});
test('leap stays aloft, float adds height and fall returns to the ground',()=>{const h=harness(),sprite=h.sprites.get(h.user);h.adapter.cue(B.step('leap',{height:2,duration:10}),0);h.adapter.pose(h.adapter.context.homes,10);assert.equal(sprite._rrLift,2);h.adapter.cue(B.step('float',{height:1,duration:10}),10);h.adapter.pose(h.adapter.context.homes,20);assert.equal(sprite._rrLift,3);h.adapter.cue(B.step('fall',{height:0,duration:10}),20);h.adapter.pose(h.adapter.context.homes,30);assert.equal(sprite._rrLift,0);h.adapter.cleanup();});
test('preview resumes beyond a blocking zero-duration sound instead of ending at the wait prefix',()=>{const Editor=vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../src/database/DatabaseActionSequenceEditor.js'),'utf8')+';DatabaseActionSequenceEditor',{ReactorBattleData:B});const editor=Object.create(Editor.prototype);Object.assign(editor,{sequence:sequence([B.step('sound',{duration:0,waitForCompletion:true}),B.step('wait',{duration:60}),B.step('impact')],'action'),db:{data:{actionSequences:[null]}},frame:0,previewLastFrame:0,previewWaitIndex:0,previewWait:{isPlaying:()=>false},previewTickets:[],sounds:[],playing:true,loop:false,previewCues(){}});editor.advancePreview(1);assert.equal(editor.frame,1);assert.equal(editor.playing,true);assert.equal(editor.previewWaitIndex,undefined);});

function visualHarness(){
 const h=harness(),children=[],shared={width:768,height:768,canvas:{},isReady:()=>true,destroy(){throw Error('shared icon atlas must survive cleanup');}};
 class Bitmap{constructor(w,h){this.width=w;this.height=h;this.canvas={};}fillAll(c){this.color=c;}isReady(){return true;}destroy(){this.destroyed=true;}}
 class Graphic{constructor(bitmap){this.bitmap=bitmap;this.anchor={set:(x,y)=>this.grip={x,y}};this.scale={set:v=>this.size=v};}setFrame(x,y,width,height){this._frame={x,y,width,height};}removeFromParent(){const i=children.indexOf(this);if(i>=0)children.splice(i,1);}destroy(){this.destroyed=true;}}
 Object.assign(h.globals,{Sprite:Graphic,Bitmap,ImageManager:{iconWidth:48,loadSystem:()=>shared,loadPicture:()=>shared}});h.manager._spriteset._battleField={addChild:g=>children.push(g)};
 for(const s of h.sprites.values())s._frame={width:48,height:96};h.user.equips=()=>[{iconIndex:37}];h.a.equips=()=>[{iconIndex:48}];h.action.item=()=>({iconIndex:73,damage:{type:1}});return {...h,children,shared};
}
test('starter library contains valid editable common actions and never overwrites records',()=>{
 const custom={...B.template('Unarmed Punch'),note:'Keep my work'};const records=[null,custom];const added=B.addStarters(records);assert.ok(added.some(s=>s.name==='Throw Item'));assert.ok(added.some(s=>s.name==='Hold Equipped Item'&&s.purpose==='routine'));assert.equal(records[1],custom);assert.equal(B.addStarters(records).length,0);for(const s of records.filter(Boolean))assert.deepEqual(B.validateSequence(s),[],s.name);
 for(const name of ['Throw Item','Throw Weapon','Boomerang']){const cues=B.timeline(B.template(name)),flight=cues.find(c=>c.step.type==='projectile'),impact=cues.find(c=>c.step.type==='impact');assert.ok(impact.start>=flight.end,name+' applies after arrival');}
});
test('flat held items use the selected battler equipment, follow movement and mirror their hand',()=>{
 const h=visualHarness(),s=h.sprites.get(h.a);h.adapter.cue(B.step('weapon',{role:'target',attachment:'rightHand'}),0);h.adapter.visuals.pose(0);const item=h.children[0];assert.equal(item._frame.y,144);const first=item.x;s.x+=80;h.adapter.visuals.pose(1);assert.ok(Math.abs(item.x-first-80)<1e-8);s._rrSequenceFacing=-90;h.adapter.visuals.pose(2);assert.ok(item.x<s.x);s._rrSequenceFacing=90;h.adapter.visuals.pose(3);assert.ok(item.x>s.x);h.adapter.cue(B.step('weapon',{role:'target',visible:false}),4);assert.equal(h.children.length,0);h.adapter.cleanup(true);
});
test('item flights fan out to unique allies, arc above endpoints and preserve impact repeats',()=>{
 const h=visualHarness();h.a.isActor=()=>true;h.b.isActor=()=>true;h.user.friendsUnit=()=>({members:()=>[h.user,h.a,h.b]});const step=B.step('projectile',{iconSource:'action',destination:'allTargets',duration:20,arc:2,spin:10});h.adapter.cue(step,0);h.adapter.visuals.pose(0);assert.equal(h.children.length,2);assert.equal(h.children[0]._frame.x,9*48);const flight=h.adapter.visuals.flights[0],from={...flight.point};h.adapter.visuals.pose(10);assert.ok(flight.point.z>from.z+1.9);assert.equal(flight.graphic.rotation,100*Math.PI/180);h.adapter.visuals.pose(20);assert.equal(flight.graphic.visible,false);assert.equal(flight.point.x,h.sprites.get(h.a).x/48);h.adapter.cue(B.step('impact',{role:'allTargets'}),20);while(h.adapter.pendingImpact)h.adapter.resolveNext();assert.deepEqual(h.calls.filter(c=>c[0]==='hit').map(c=>c[1]),[1,1,2]);h.adapter.cleanup();assert.equal(h.children.length,0);
});
test('returning flights return to the launch point and cancellation releases private bitmaps only',()=>{
 const h=visualHarness();h.adapter.cue(B.step('projectile',{duration:20,arc:1,flight:'return'}),0);h.adapter.visuals.pose(0);const flight=h.adapter.visuals.flights[0],initial={...flight.point},bitmap=flight.graphic.bitmap;h.adapter.visuals.pose(10);assert.equal(flight.point.x,h.sprites.get(h.a).x/48);h.adapter.visuals.pose(20);assert.deepEqual({...flight.point},initial);h.adapter.cleanup(true);assert.equal(bitmap.destroyed,true);assert.equal(h.manager._spriteset._rrSequenceVisualUpdates.size,0);
});
test('hand attachment resolves actual animated 3D bones and keeps offsets in logical coordinates',async()=>{
 const THREE=await import('three'),scope={THREE,ReactorBattleData:B};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../../runtime/reactor_battle_room.js'),'utf8'),scope);const Room=scope.ReactorBattleRoomView,object=new THREE.Group(),bone=new THREE.Bone();bone.name='mixamorig:RightHand';bone.position.set(.3,1.2,0);object.add(bone);object.position.set(5.5,0,3.5);const record={object,spec:{size:2},position:{x:5,y:3,z:0,facing:90}},view=Object.create(Room.prototype);view.models=new Map([['user',record]]);view.billboards=new Map();const step={attachment:'rightHand',x:.1,z:.2};let p=view.attachmentPoint('user',step);assert.ok(Math.abs(p.x-5.4)<1e-8);assert.equal(p.y,3);assert.equal(p.z,1.4);bone.position.y=1.8;p=view.attachmentPoint('user',step);assert.equal(p.z,2);assert.equal(Room.attachmentWorld(record,'rightHand','missing'),null);const fallback=view.attachmentPoint('missing',step,{x:0,y:0,z:0,facing:-90});assert.ok(fallback.x<0);assert.ok(fallback.z>0);
});
test('fresh project data includes real editable starter records',()=>{
 const ProjectManager=vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../src/ProjectManager.js'),'utf8')+';ProjectManager',{ReactorBattleData:B,RRJson:{parse:JSON.parse}});const pm=Object.create(ProjectManager.prototype),data=pm.getStarterData('Starter test');assert.equal(data['ActionSequences.json'].filter(Boolean).length,19);assert.ok(data['ActionSequences.json'].some(s=>s?.name==='Throw Item'));B.validateStore(data['ActionSequences.json'],B.empty());const original=[null,{...B.template('Unarmed Punch'),note:'Authored template'}];let saved;Object.assign(pm,{path,fs:{existsSync:file=>file.endsWith('ActionSequences.json'),readFileSync:()=>JSON.stringify(original)},writeProjectMetadata(){},writeJson(file,value){saved=value;}});pm.updateCopiedTemplateProject('/fixture','Copy','0.98.6');assert.equal(saved[1].note,'Authored template');assert.equal(saved.filter(Boolean).length,19);
});
test('humanoid item fallback animates a release while preserving authored motions',async()=>{
 const THREE=await import('three'),scope={THREE,Reactor3D:{readModelAnimationRules:s=>s.animations}};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../../runtime/reactor_battle_room.js'),'utf8'),scope);
 const object=new THREE.Group(),arm=new THREE.Bone(),fore=new THREE.Bone(),hand=new THREE.Bone();arm.name='RightArm';fore.name='RightForeArm';hand.name='RightHand';arm.position.set(.3,1.5,0);fore.position.set(0,-.4,0);hand.position.set(0,-.4,0);object.add(arm);arm.add(fore);fore.add(hand);const skin=new THREE.Object3D();skin.isSkinnedMesh=true;skin.skeleton={bones:[arm,fore,hand]};object.add(skin);const authored={trigger:'action',name:'punch',clip:'custom-punch'},record={object,rules:[authored],binding:{root:object,clips:[]}};scope.ReactorBattleRoomView.prepareMotions(record);assert.equal(record.rules.find(r=>r.name==='punch'),authored);assert.equal(record.rules.find(r=>r.name==='attack').clip,'custom-punch');const item=record.rules.find(r=>r.name==='item');assert.ok(item);const clip=record.binding.clips.find(c=>c.name===item.clip);assert.ok(clip.tracks.every(t=>t.times.some(time=>Math.abs(time-.2)<.001)));const action=record.binding.mixer.clipAction(clip);action.play();object.updateMatrixWorld(true);const start=hand.getWorldPosition(new THREE.Vector3());record.binding.mixer.setTime(.2);object.updateMatrixWorld(true);assert.ok(hand.getWorldPosition(new THREE.Vector3()).distanceTo(start)>.1);const count=record.binding.clips.length;scope.ReactorBattleRoomView.prepareMotions(record);assert.equal(record.binding.clips.length,count);
});
test('preview equipment slots distinguish shields from dual-wielded weapons with matching IDs',()=>{
 const Editor=vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../src/database/DatabaseActionSequenceEditor.js'),'utf8')+';DatabaseActionSequenceEditor',{ReactorBattleData:B});const record={id:1,classId:1,equips:[2,2],traits:[]},klass={traits:[]},weapon={id:2,iconIndex:19},shield={id:2,iconIndex:87},ed=Object.create(Editor.prototype);Object.assign(ed,{castKinds:{user:'actors'},cast:{user:1},ui:{settings:()=>B.empty()},db:{getActor:()=>record,getClass:()=>klass,getWeapon:()=>weapon,getArmor:()=>shield}});assert.equal(B.visualIcon({iconSource:'weapon',equipIndex:2},ed.previewBattler('user')),87);klass.traits.push({code:55,dataId:1});assert.equal(B.visualIcon({iconSource:'weapon',equipIndex:2},ed.previewBattler('user')),19);
});
test('a held model turns about its grip, faces where its holder faces, and tweens every turn',async()=>{
 // Placement: an authored front face takes the holder's facing itself; a model without one keeps the long-axis +90.
 const at={x:5,y:3,z:1.5};
 assert.deepEqual(B.heldPlacement(at,90,{rotation:20,rotateY:10,rotateZ:5,scale:2,gripY:0},{faces:{front:[1,0,0]}}),{x:5,y:3,z:1.5,facing:90,rotateX:-20,rotateY:10,rotateZ:5,scale:2,pivotY:0});
 const plain=B.heldPlacement(at,90,{},{});assert.equal(plain.facing,180);assert.equal(plain.pivotY,.5);assert.equal(plain.scale,1);
 // The tween carries Turn and Roll along with the rest.
 assert.deepEqual(B.heldPose({x:0,rotation:0,rotateY:0,rotateZ:0,scale:1},{x:1,rotation:90,rotateY:40,rotateZ:-20,scale:3},.5),{x:.5,y:0,z:0,rotation:45,rotateY:20,rotateZ:-10,scale:2});
 // The room view brings the grip point, not the feet, to the placed position, after the turn.
 const THREE=await import('three'),scope={THREE,ReactorBattleData:B,Reactor3D:{applyEventModelPose:(o,spec)=>{o.rotation.order='YXZ';o.rotation.set(spec.pitch||0,spec.yaw||0,spec.roll||0);}}};
 vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../../runtime/reactor_battle_room.js'),'utf8'),scope);
 const Room=scope.ReactorBattleRoomView,object=new THREE.Group(),record={object,spec:{size:1},position:{},extent:{x:.5,y:2,z:.5},scale:1},view=Object.create(Room.prototype);view.models=new Map([['held',record]]);view.billboards=new Map();
 view.place('held',{x:4,y:6,z:1.5,facing:0,pivotY:.5});
 assert.ok(Math.abs(object.position.y-.5)<1e-9,'the middle of a two-tile model sits at the hand: '+object.position.y);
 view.place('held',{x:4,y:6,z:1.5,facing:0,pivotY:0});assert.ok(Math.abs(object.position.y-1.5)<1e-9,'held by the base, the feet sit at the hand');
 view.place('held',{x:4,y:6,z:1.5,facing:0,rotateX:90,pivotY:.5});
 assert.ok(Math.abs(object.position.y-1.5)<1e-6&&Math.abs(object.position.z-(6.5-1))<1e-6,'tipped flat, the grip offset lies along the ground: '+object.position.toArray());
});
test('preview choices are remembered per sequence and dropped when their records are gone',()=>{
 const store=new Map(),localStorage={getItem:k=>store.has(k)?store.get(k):null,setItem:(k,v)=>store.set(k,String(v))};
 const Editor=vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../src/database/DatabaseActionSequenceEditor.js'),'utf8')+';DatabaseActionSequenceEditor',{ReactorBattleData:B,localStorage,JSON});
 const make=weapons=>{const ed=Object.create(Editor.prototype);Object.assign(ed,{parent:{currentProject:{path:'/p'}},db:{getWeapon:id=>weapons.includes(id)?{id}:null},sequence:{id:7},cast:{user:1,target:1},castKinds:{user:'actors',target:'enemies'},targetCount:1,mirrored:false,sampleWeapon:0,previewProjection:'3d',scene:{kind:'grid'},controls:{distance:14}});return ed;};
 const first=make([49]);Object.assign(first,{cast:{user:3,target:2},castKinds:{user:'enemies',target:'enemies'},targetCount:3,mirrored:true,sampleWeapon:49,sampleAction:'items:5',previewProjection:'2d',scene:{kind:'troop',id:4}});first.controls.distance=9;first.savePrefs();
 const second=make([49]),extra=second.loadPrefs();
 assert.deepEqual([second.cast,second.castKinds,second.targetCount,second.mirrored,second.sampleWeapon,second.previewProjection,second.scene],[{user:3,target:2},{user:'enemies',target:'enemies'},3,true,49,'2d',{kind:'troop',id:4}]);
 assert.deepEqual({...extra},{sampleAction:'items:5',distance:9,follow:false,orbit:null,pan:null});
 const other=make([49]);other.sequence={id:8};other.loadPrefs();assert.equal(other.targetCount,1,'another sequence keeps its own cast');assert.equal(other.previewProjection,'2d','projection and scene are shared across sequences');
 const gone=make([]);gone.loadPrefs();assert.equal(gone.sampleWeapon,0,'a deleted preview weapon is forgotten');
 store.set('rrSequencePreview:/p','not json');assert.doesNotThrow(()=>make([]).loadPrefs());
});
test('pose steps become keyed rules that start where the part stood and stay put, carried by part name',()=>{
 const seq={version:1,steps:[B.step('motion',{motion:B.POSE_MOTION,duration:20,parts:[{part:'RightLowerArm',rotate:[90,0,0]}]}),B.step('wait',{duration:10}),B.step('motion',{motion:B.POSE_MOTION,duration:10,parts:[{part:'RightUpperArm',rotate:[0,0,-40]}]}),B.step('motion',{motion:B.POSE_MOTION,duration:6,resetPose:true})]};
 const [first,wait,second,reset]=seq.steps,plan=B.posePlan(seq);
 assert.equal(B.motionActionName(first),'pose:'+first.id);assert.equal(B.spriteMotionName(first),'idle');assert.equal(B.hasPose(wait),false);
 assert.deepEqual(plan.rules[first.id].map(r=>[r.part,r.keys[0].rotate,r.keys[1].rotate,r.period,r.stay,r.trigger]),[['RightLowerArm',[0,0,0],[90,0,0],10,true,'action']]);
 // The second pose keeps the elbow where the first left it while it raises the upper arm.
 assert.deepEqual(plan.rules[second.id].map(r=>r.part+':'+r.keys[0].rotate+'>'+r.keys[1].rotate).sort(),['RightLowerArm:90,0,0>90,0,0','RightUpperArm:0,0,0>0,0,-40']);
 // Starting from rest sends every posed part home over the step.
 assert.deepEqual(plan.rules[reset.id].map(r=>r.part+':'+r.keys[0].rotate+'>'+r.keys[1].rotate).sort(),['RightLowerArm:90,0,0>0,0,0','RightUpperArm:0,0,-40>0,0,0']);
 assert.deepEqual(plan.releases,{},'no plain motion followed a pose here');
 // A plain motion after a pose releases the posed parts over its own frames and still plays its motion under the release's action.
 const walkSeq={version:1,steps:[B.step('motion',{motion:B.POSE_MOTION,duration:20,parts:[{part:'RightLowerArm',rotate:[90,0,0]}]}),B.step('motion',{motion:'walk',duration:12}),B.step('motion',{motion:'idle',duration:0})]};
 const [pose,walk,idle]=walkSeq.steps,walkPlan=B.posePlan(walkSeq);
 assert.equal(walkPlan.actions[walk.id],'pose:'+walk.id);assert.equal(walkPlan.releases[walk.id],'walk');assert.equal(B.motionActionName(walk,walkPlan),'pose:'+walk.id);
 assert.deepEqual(walkPlan.rules[walk.id].map(r=>r.part+':'+r.keys[0].rotate+'>'+r.keys[1].rotate+':p'+r.period),['RightLowerArm:90,0,0>0,0,0:p6']);
 assert.equal(walkPlan.rules[idle.id],undefined,'once released, the next motion is plain again');assert.equal(B.motionActionName(idle,walkPlan),'idle');
 const modelRules=[{name:'walk',trigger:'action',type:'clip',clip:'Walking'},{name:'Walk',trigger:'walking',type:'clip',clip:'Walking'},{name:'punch',trigger:'action',type:'clip',clip:'P'}];
 assert.deepEqual(B.releaseMotionRules(walkPlan,walk.id,modelRules).map(r=>r.name+'/'+r.clip),['pose:'+walk.id+'/Walking']);
 const snap=B.posePlan({version:1,steps:[pose,B.step('motion',{motion:'idle',duration:0})]});assert.equal(Object.values(snap.rules)[1][0].period,1,'no frames: a snap');
 assert.equal(B.partLabel('RightLowerArm'),'Right Forearm (elbow)');assert.equal(B.partLabel('Full-Turret'),'Full Turret');assert.equal(B.hingeAxis([0,-1,0]),0);assert.equal(B.hingeAxis([1,0,0]),1);
 assert.deepEqual(B.validateSequence({version:1,steps:[B.step('motion',{motion:B.POSE_MOTION,parts:[{}]})]}).filter(m=>m.includes('Pose')),['Pose parts must name a model part.']);
});
test('a staying keyed pose holds its last key while its action stands, and the animator plays the plan',async()=>{
 const R=require('../../runtime/reactor_3d.js');global.self=global;global.window=global;require(path.join(__dirname,'../../runtime/libs/three.js'));const THREE=global.THREE;
 const read=R.readModelAnimationRules({animations:[{type:'pose',trigger:'action',name:'lift',part:'Arm',keys:[{at:1,rotate:[0,0,45]}],stay:true,period:10}]})[0];
 assert.equal(read.stay,true);assert.equal(R.modelRuleDuration(read),Infinity);
 assert.equal(R.readModelAnimationRules({animations:[{type:'pose',trigger:'action',name:'x',part:'Arm',stay:true}]})[0].stay,false,'stay needs keys');
 // A carved part turned by a pose step's rules: halfway there mid-step, all the way after, still there long after.
 const root=new THREE.Group(),arm=new THREE.Mesh(new THREE.BoxGeometry(1,1,1),new THREE.MeshBasicMaterial());arm.userData.parts=[{name:'Arm',pivot:[0,0,0]}];root.add(arm);
 const binding=R.prepareModelInstance(root,[]),step=B.step('motion',{motion:B.POSE_MOTION,duration:20,parts:[{part:'Arm',rotate:[0,0,90]}]}),rules=B.partPoseRules(step,{}).rules;
 const angle=()=>{root.updateMatrixWorld(true);return Math.round(new THREE.Euler().setFromQuaternion(arm.quaternion,'XYZ').z*180/Math.PI)+0;};
 const at=frame=>{R.applyModelAnimation(binding,rules,{frame,moving:false,distance:0,scale:1,action:{name:rules[0].name,frame:0},seek:true});return angle();};
 assert.equal(at(0),0);const mid=at(10);assert.ok(mid>20&&mid<70,'part way there: '+mid);assert.equal(at(20),90);assert.equal(at(500),90,'kept while the action stands');
 R.applyModelAnimation(binding,rules,{frame:600,moving:false,distance:0,scale:1,action:{name:'other',frame:590}});assert.equal(angle(),0,'another action drops it');
});
